### PR TITLE
Build gmp the correct way

### PR DESCRIPTION
**Pull request by delcypher**
The previous method of building had lots of problems
- Each variant would be the same object file multiple times which
  is very inefficient.
- Due to the above the linker also had to work much harder due
  to not linking against a library
- It is not portable as the build of gmp was using the config
  of a different machine rather than the host.

This PR instead teaches CMake to build libgmp as an external project and then imports the static library targets which the benchmarks then link against.

The benchmarks link against the library using the [newly added support for out of tree dependencies](https://github.com/delcypher/fp-bench/commit/c41c85b99aeae87ad3df1e51c730265fd50a7ab7) so you need to update to the latest version of fp-bench for this to all work.

Please note I had to drop in vanilla sources for gmp-6.1.1 because what's in the repo was broken (it looked like a configure had been run in source and some of the source files had defines added).

@ccadar @afd : This might interest you.

### CODE REVIEW

**Comment by danielschemmel** [comment]
You are quite right, the sources were configured so that they could be compiled by simply tossing all of them into a c compiler.
Once my final testing is done today, I will (assuming everything goes right) accept this pull request.

**Comment by delcypher** [comment]
@danielschemmel Did you finish testing this?

**Comment by delcypher** [comment]
@danielschemmel ping.

**Comment by delcypher** [comment]
Damn looks like I accidently broke the source file locations in the `spec.yml` file. This needs a little more work!

**Comment by delcypher** [comment]
@danielschemmel The counter example locations in the `spec.yml` file are now fixed.

**Pull request merged**
